### ISSUE TITLE
Doesn't set field using C# 6 syntax

### ISSUE THREAD

**Issue by StephenGilboy** [danielwertheim/jsonnet-privatesetterscontractresolvers#1]
I've noticed that it cannot set values on fields that are using the C# 6 get syntax. 

```
public class Entity {
  private readonly string _id;
  public string Id => _id;

  public Entity(string id) {
    _id = id;
  }
}
```

**Comment by danielwertheim** [comment]
If we don't look at the `PrivateSetterContractResolver` JSON.Net should be able to handle the above case, since it can make use of the constructor.

The `PrivateSetterContractResolvers` are not made for attempting to set backing fields. Only properties and will in this case fail, since the construct above has no setter.

Would you like it to operate on all fields, private fields, only backing fields?

**Comment by StephenGilboy** [comment]
Automapper seems to act upon all properties that are public, with private fields, so I could see where it would be expected that `Json.Convert()` would handle it the same way.  For my value types I usually have them written as: 

```
public sealed class Schedule {
  private DateTime _startDate;
  private DateTime _endDate;
  public DateTime StartDate => _startDate;
  public DateTime EndDate => _endDate;
  
  private Schedule() { }
  public static Schedule(DateTime startDate, DateTime endDate) {
    // Logic to make sure Schedule is in a valid state before creating it
    return new Schedule() {
        _startDate = startDate;
        _endDate = endDate;
    }
  }
} 
```
so coming back from DocumentDb I'd expect my schedule to be rehydrated within the entity.

**Comment by danielwertheim** [comment]
And should the convention be `PropName => _propName` or ....?

Not keen on just finding all private fields... as there might be cases where someone don't want private fields to be hydrated.... as they are in fact private.

BTW, Why not have the constructor take the read only args and allow JSON.Net to work on non public constructors?

**Comment by danielwertheim** [comment]
Project is being archived.
