### ISSUE TITLE
time to turn this into a .net core package?

### ISSUE THREAD

**Issue by julielerman** [danielwertheim/jsonnet-privatesetterscontractresolvers#2]
I copy/pasted the class into my own class in a solution and it works just fine. Does it make sense to create a core clr version of this?

**Comment by danielwertheim** [comment]
Absolutely. Will fix.

**Comment by shawnmclean** [comment]
NetStandard would be nice please :)

**Comment by SimplerSoftware** [comment]
Bump ;)

**Comment by danielwertheim** [comment]
https://www.nuget.org/packages/JsonNet.PrivateSettersContractResolvers
